SHOW TABLES;

SHOW VIEWS;

-- SELECT COUNT(*) FROM RAW_MOVIES;
SELECT COUNT(*) FROM SRC_MOVIES;
SELECT * FROM SRC_MOVIES;

-- SELECT * FROM RAW_RATINGS;
SELECT * FROM SRC_RATINGS;

-- SELECT * FROM RAW_LINKS;
SELECT * FROM SRC_LINKS;

-- SELECT * FROM RAW_GENOME_TAGS;
SELECT * FROM SRC_GENOME_TAGS;

-- SELECT * FROM RAW_GENOME_SCORES;
SELECT * FROM SRC_GENOME_SCORES;

-- SELECT * FROM RAW_TAGS;
SELECT * FROM SRC_TAGS;





