
SELECT * FROM SRC_MOVIES;

SELECT * FROM DIM_MOVIES;

SELECT * FROM DIM_USERS;

SELECT * FROM DIM_GENOME_TAGS;


SELECT * FROM FACT_GENOME_SCORES;

SELECT * FROM SRC_RATINGS;

-- DROP Table FACT_RATINGS;

SELECT * FROM FACT_RATINGS Order By RATING_TIMESTAMP desc limit 10;

SELECT * FROM SRC_RATINGS Order By RATING_TIMESTAMP desc limit 10;

INSERT INTO SRC_RATINGS
Values(777,7777,1,'2015-04-30 23:40:02.000 -0700');

--Seeds
SELECT *  FROM MART_MOVIE_RELEASEDATES ORDER BY STAGE ASC;

SELECT *  FROM MOVIELENS.RAW_DEV.SRC_R_MOVIES;

SELECT * FROM src_tags;




